# Use a newer version of the SDK to fix the virtual package detection for macOS
# Otherwise `SYSTEM_VERSION_COMPAT` needs to be set to `0` to detect the proper macOS version
MACOSX_SDK_VERSION:            # [osx and x86_64]
  - 11.0                       # [osx and x86_64]
c_compiler:        # [win]
  - vs2019         # [win]
cxx_compiler:      # [win]
  - vs2019         # [win]
c_stdlib_version:  # [win]
  - 2019.11        # [win]
